-- SQL to create the assessments table in Supabase

CREATE TABLE assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_phone TEXT,
  patient_region TEXT,
  patient_nation TEXT,
  risk_habits JSONB,
  risk_score INTEGER,
  provisional_diagnosis TEXT,
  identified_lesions TEXT[],
  summary TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security)
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert (for demo purposes)
-- In a production app, you should restrict this to authenticated users
CREATE POLICY "Allow anonymous inserts" ON assessments
  FOR INSERT WITH CHECK (true);

-- Create a policy that allows anyone to read (optional, for demo purposes)
CREATE POLICY "Allow anonymous reads" ON assessments
  FOR SELECT USING (true);
